README.md
J'ai ajouté le fait de respecter les conventionnal commits + pas de BC sauf détaillé + mis à jour le lien vers le site officiel
=> docs: adding conventionnal commits and updating links

src/main/java/fr/communaywen/core/utils/ItemBuilder.java
Rajout d'un script permettant de facilement créer des item avec une ligne : 
ItemStack items = new ItemBuilder(Material.PLAYER_HEAD).setName("").toItemStack();
=> Adding ItemBuilder for create item easier.

src/main/java/fr/communaywen/core/utils/MOTDChanger.java
It's a PoC, it should normally work as expected
=> Code: Add MOTD Changer (PoC)

.github/workflows/main.yml, build.gradle
Le shadowJar permet d'inclure les dépendances dans le jar.
_"Un shadowjar, aussi appelé "fat jar" ou "uber jar", est un fichier JAR qui contient tout le code et les dépendances nécessaires pour exécuter une application Java. Il est créé à l'aide d'un plugin Gradle appelé Shadow."_
https://imperceptiblethoughts.com/shadow/
=> Add shadowJar build

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/utils/VersionCommand.java, src/main/resources/plugin.yml
Should add the command /version for the project
=> Code: Command Version

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/utils/MOTDChanger.java
Update the behaviour to avoid initializing two times the code from AywenCraftPlugin.java and MOTDChanger.java
=> Code: Update Code Behaviour

src/main/java/fr/communaywen/core/utils/MOTDChanger.java
=> Code: Reimport Java

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/VersionCommand.java
Add Command Folder and swipe VersionCommand from utils to commands
=> Code: Create Commands Folder

.gitignore
=> Ajout d'un .gitignore (Gradle, IntelliJ, Eclipse, VSCode)

src/main/java/fr/communaywen/core/commands/VersionCommand.java, src/main/resources/plugin.yml
This update add permission, to check if permissions works with LuckPerms
=> Code: Add Permission

build.gradle
Afin de développer dans un environnement plus sûr, je propose d'ajouter cette dépendance.
=> [Code] Ajout de la dépendance JetBrains annotations

src/main/java/fr/communaywen/core/AywenCraftPlugin.java
Permet une meilleur tracabilité
=> [Code] Utilisation du logger du plugin au lieu de celui de Bukkit

src/main/java/fr/communaywen/core/commands/ProutCommand.java
When user use /prout command, a broadcast to the server will be add, and the user will have a glowing effect for 30 seconds
=> Code: Update Prout

src/main/java/fr/communaywen/core/commands/ProutCommand.java
Update the prout command with cooldown, and green glowing
=> Code: Prout Update V2

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/listeners/ChatListener.java, src/main/java/fr/communaywen/core/utils/DiscordWebhook.java
Discord Webhook Update (PoC)
(Do not merge now)
=> Code: Discord Webhook Update

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/RulesCommand.java, src/main/resources/plugin.yml, src/main/resources/rules.yml
J'ai ajouté une commande pour ouvrir le livres de règles: /rules ou /regles
Les règles sont issues de rules.yml
=> [Feature] Add Rules Book

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/RTPCommand.java, src/main/resources/config.yml
*Avez vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?*
=> Là normalement c'est bon

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/RTPCommand.java, src/main/resources/config.yml
=> le RTP + la config (encore mais là ca marche (vraiment))

src/main/java/fr/communaywen/core/teams/menu/MemberListMenu.java, src/main/java/fr/communaywen/core/teams/menu/TeamListMenu.java
- Removed close button on member list menu
- Changed return button place
=> Esthetic change

src/main/resources/plugin.yml
Petit problème dans plugin.yml résolu
=> Bug des commandes résolu

src/main/java/fr/communaywen/core/commands/TeamCommand.java, src/main/java/fr/communaywen/core/teams/Team.java, src/main/java/fr/communaywen/core/teams/TeamManager.java, src/main/java/fr/communaywen/core/teams/menu/MemberListMenu.java, src/main/java/fr/communaywen/core/teams/menu/TeamListMenu.java
Résolu problème faisant qu'on puisse créer une deuxieme team en se déconnectant puis reconnectant
=> Fixed 2 teams problem

src/main/resources/plugin.yml
=> Remove rtp

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/RTPCommand.java, src/main/resources/config.yml
=> RTP config optimisé

src/main/java/fr/communaywen/core/commands/TeamCommand.java, src/main/java/fr/communaywen/core/teams/Team.java
Il y'a maintenant un inventaire commun accessible via /team inventory !
=> Added inventory for all team members

build.gradle, src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/CreditCommand.java, src/main/java/fr/communaywen/core/utils/GitHubAPI.java, src/main/resources/plugin.yml
J'ai écris une commande pour afficher les contributeurs dans l'ordre
=> [Command] /credit affiche les credits via l'API Github

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/listeners/SleepListener.java
Ajout d'un listener SleepListener permettant de passer la nuit quand
un certain pourcentage de joueur dorment la nuit (ou pendants un orage).
Ce pourcentage est décidé suivant le nombre de personnes présents
dans le monde
=> Passer la nuit plus facilement

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/TeamCommand.java, src/main/java/fr/communaywen/core/teams/Team.java, src/main/java/fr/communaywen/core/teams/TeamManager.java, src/main/java/fr/communaywen/core/teams/menu/TeamListMenu.java, src/main/java/fr/communaywen/core/teams/menu/TeamMenu.java, src/main/java/fr/communaywen/core/teams/utils/TeamUtils.java, src/main/java/fr/communaywen/core/utils/database/DatabaseConnection.java, src/main/java/fr/communaywen/core/utils/database/DatabaseManager.java, src/main/resources/config.yml
@Xernas78 J'ai désactivé l'inventaire de team parce que flemme de trouver un moyen de l'stocker dans la db + mon code est vraiment bancal + il y a pas de cache x) Mais bon, ça fait l'taff
=> Added database integration

src/main/java/fr/communaywen/core/teams/Team.java, src/main/java/fr/communaywen/core/teams/TeamManager.java
Le bug il vient pas de moi, ez.
=> [Code] Patched bug on team quit.

build.gradle, src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/LinkCommand.java, src/main/java/fr/communaywen/core/listeners/OnPlayers.java, src/main/java/fr/communaywen/core/utils/DraftAPI.java, src/main/java/fr/communaywen/core/utils/LinkerAPI.java, src/main/resources/plugin.yml
J'ai rajouté des permissions
ayw.levels.x0 (10, 20, 30, 40, 50...)
ayw.levels.0 n'existe pas
Votre pseudo Minecraft **dois** être le même que votre username (et pas displayName) discord *en lowercase*
=> Permissions lié au rank DraftBot

build.gradle, src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/FeedCommand.java, src/main/java/fr/communaywen/core/commands/RTPCommand.java, src/main/java/fr/communaywen/core/listeners/RTPWand.java, src/main/resources/config.yml, src/main/resources/plugin.yml
Ajout du RTPwand + optimisation
(Ajout de ItemsAdder API)
=> Ajout du RTPwand + optimisation

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/RTPCommand.java
Résolution de bug :
An unexpected error occurred trying to execute that command pour le /rtp
Et le /feed qui ne marchait pas bien
=> Résolution de bug 

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/FeedCommand.java, src/main/java/fr/communaywen/core/commands/RTPCommand.java, src/main/java/fr/communaywen/core/listeners/RTPWand.java, src/main/java/fr/communaywen/core/tpa/CommandTPA.java, src/main/java/fr/communaywen/core/tpa/CommandTpaccept.java, src/main/java/fr/communaywen/core/tpa/CommandTpdeny.java, src/main/java/fr/communaywen/core/tpa/TPAQueue.java, src/main/java/fr/communaywen/core/tpa/TPARequest.java, src/main/resources/config.yml
Ajout du /tpa j'espère que qlq ne le faisait pas aussi + Optimisation du /rtp + J'ai mis 10 à la place de 20 dans le setFoodLevel 😅 pour le /feed (là c'est bon)
=> Ajout du /tpa j'espère que qlq ne le faisait pas aussi

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/RTPCommand.java, src/main/java/fr/communaywen/core/listeners/RTPWand.java, src/main/java/fr/communaywen/core/tpa/CommandTpaccept.java, src/main/resources/plugin.yml
J'ai retiré les Scheduler qui ne marchait pas + petite modification du fichier plugin.yml
=> J'ai retiré les Scheduler qui ne marchait pas

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/ManualLinkCommand.java, src/main/java/fr/communaywen/core/listeners/OnPlayers.java, src/main/java/fr/communaywen/core/utils/LinkerAPI.java
Pour lier un compte il y a seulement /manuallink <id discord>
Ca l'ajoutera à la table pour créer la table c'est "CREATE TABLE link (discord_id VARCHAR(100) NOT NULL, minecraft_uuid VARCHAR(100))"
=> J'ai partiellement créer le lien entre discord et minecraft

src/main/java/fr/communaywen/core/utils/LinkerAPI.java, src/main/java/fr/communaywen/core/utils/database/DatabaseConnection.java, src/main/java/fr/communaywen/core/utils/database/DatabaseManager.java
Changement de this.getTeamConnection car ce n'est pas dédié que au team, ansi que les fichiers qui l'utilise (LinkerApi.java)
=> Correction Database

CONTRIBUTING.md
*Avez vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?*
Oui
Correction de pas mal de fautes dans CONTRIBUTING.md.
=> Correction des fautes dans CONTRIBUTING.md

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/ManualLinkCommand.java, src/main/java/fr/communaywen/core/listeners/StarterKits.java, src/main/java/fr/communaywen/core/utils/LinkerAPI.java
J'ai ajouté des starters kits en fonction des permissions ayw.levels.x0
=> Starter Kits

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/listeners/WelcomeMessage.java, src/main/resources/welcomeMessageConfig.yml
Ajout de WelcomeMessage qui affiche un title à la
première connection du joueur. Ajout du fichier
WelcomeMessageConfig.yml pour configurer ce title. 
Ajout de l'event dans AywenCraftPlugin.
=> [feature] Ajoute un title à la première connection

src/main/java/fr/communaywen/core/listeners/WelcomeMessage.java
Affiche à mon joueur le title même si il n'est pas nouveau joueur.
Sera supprimé à la prochaine PR.
=> Ajoute un debug pour tester sur le serveur

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/MoneyCommand.java
L'ajout tous simple d'un TabCompleter.
=> [Features] Ajout d'un TabCompleter pour la commande /money

src/main/java/fr/communaywen/core/AywenCraftPlugin.java
Changement du 
`private EconomyManger economyManager`
en 
`public EconomyManager economyManager`
pour faciliter l'utilisation de l'economyManager.
=> Changement du private EconomyManager en public EconomyManager

src/main/java/fr/communaywen/core/commands/MoneyCommand.java
J'ai update le tabcompleter, j'ai oublier de mettre les players en args 2
=> [Features] Update du TabCompleter pour la cmd Money

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/QuizManager.java, src/main/java/fr/communaywen/core/listeners/ChatListener.java, src/main/resources/quizzes.yml
*Avez vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?*
Oui
- Ajout d'un système de question réponse (dans le style du "palanimation") dans le chat:
Toute les 30 minutes (configurable) une question aléatoire est posée
Le premier a répondre gagne une somme d'argent aléatoire configurable
=> Jeu de question réponse dans le chat

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/QuizManager.java
- Rends le QuizManager reload proof
- N'update plus le quiz quand aucun joueur n'est connecté
=> Fix + optimize QuizManager

src/main/java/fr/communaywen/core/listeners/VpnListener.java
=> J'ai changé de methode qui ecoute a la connexion

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/tpa/CommandTPA.java
*Avez vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?* Oui
J'ai utilisé BukkitAudiences pour faire que le message du tpa est un message cliquable. Si tu cliques, tu acceptes la demande.
Attention, c'est la première fois que j'utilise cette api donc c'est pas sûr que ça foncitonne.
=> Message cliquable pour accepter le tpa

src/main/java/fr/communaywen/core/listeners/VpnListener.java
J'ai modifié le message de kick
Normalement, quand un joueur se fait kick, il n'y a plus le message de connexion et de déconnexion dans le chat.
=> Multiples corrections

src/main/java/fr/communaywen/core/tpa/CommandTPA.java, src/main/java/fr/communaywen/core/tpa/CommandTpaccept.java
Ajout d'une condition pour vérifier si le joueur fait une demande a lui-même pour le tpa + réparation du clickevent
=> |TPA] Ajout d'une condition pour vérifier si le joueur fait une demande a lui-même

src/main/java/fr/communaywen/core/commands/TeamCommand.java, src/main/java/fr/communaywen/core/teams/TeamManager.java
=> fix: team help command

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/staff/freeze/FreezeCommand.java, src/main/java/fr/communaywen/core/staff/players/PlayersCommand.java
Ajout de l'indexiation du /players
=> [MODIF] Ajout de l'indexiation de /players

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/MoneyCommand.java, src/main/java/fr/communaywen/core/commands/TeamCommand.java, src/main/java/fr/communaywen/core/utils/command/InteractiveHelpMenu.java, src/main/resources/plugin.yml
J'ai adapté la commande money avec la commande api
=> fix: adapting money command to new command api

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/MoneyCommand.java, src/main/java/fr/communaywen/core/utils/command/InteractiveHelpMenu.java
=> fix: add space to help command

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/utils/FreezeUtils.java
Correction de l'erreur au moment du /freeze
=> [ERREUR] /freeze

src/main/java/fr/communaywen/core/commands/SpawnCommand.java
=> Bug du /spawn résolu

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/BaltopCommand.java, src/main/java/fr/communaywen/core/commands/MoneyCommand.java, src/main/java/fr/communaywen/core/economy/EconomyManager.java
=> Ajoute la commande BaltopCommand

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/FBoomCommand.java, src/main/java/fr/communaywen/core/commands/ProutCommand.java, src/main/resources/plugin.yml
Fait que la commande **FBoom** utilise le nouveau framework de commandes
Fait que la commande **Prout** utilise le système de cooldown intégré
=> Fix commande FBoum + Other command related fixes

src/main/java/fr/communaywen/core/commands/FeedCommand.java
Le titre est assez explicite je pense
=> Repare the Feed command cooldown

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/DiscordCommand.java, src/main/java/fr/communaywen/core/commands/GithubCommand.java
/discord redirige vers le discord
/github (ou /git) redirige vers le repo du plugin
=> Ajout des commandes DiscordCommand et GithubCommand.

src/main/java/fr/communaywen/core/commands/DiscordCommand.java, src/main/java/fr/communaywen/core/commands/FeedCommand.java, src/main/java/fr/communaywen/core/commands/GithubCommand.java, src/main/java/fr/communaywen/core/listeners/PlayersMenuListener.java, src/main/java/fr/communaywen/core/utils/PlayersMenuUtils.java
Ajout de logs dans une commande pour mieux debug
=> [DEBUG] Ajout de logs

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/friends/FriendsManager.java, src/main/java/fr/communaywen/core/friends/FriendsRequest.java, src/main/java/fr/communaywen/core/friends/commands/FriendsCommand.java, src/main/java/fr/communaywen/core/listeners/FriendsListener.java, src/main/java/fr/communaywen/core/utils/FriendsUtils.java
Ajout des commandes pour le système d'ami.
Ajout du système d'ami.
Ajout du système de sauvegarde des amis.
Ajout d'un message lors de la connexion/déconnexion d'un ami.
=> Ajout du système d'ami.

src/main/java/fr/communaywen/core/friends/commands/FriendsCommand.java, src/main/java/fr/communaywen/core/listeners/FriendsListener.java
Correction du pseudo lors de la demande
Tu ne peux plus envoyer de demande à toi-même
=> Correction de deux bugs dans le système de demande d'ami.

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/listeners/SleepListener.java
Modification de SleepListener afin que minecraft gère lui même le dodo. Plutôt que ça soit sleeplistener qui change lui même le temps lorse qu'il y a un certain nombre de joueurs faisant dodo.
=> Modification de SleepListener

src/main/java/fr/communaywen/core/listeners/OnPlayers.java
=> Add Seinyy size

src/main/java/fr/communaywen/core/commands/SpawnCommand.java, src/main/java/fr/communaywen/core/tpa/TpacceptCommand.java
=> Ajout du screeneffect

src/main/java/fr/communaywen/core/staff/players/PlayersCommand.java
Suppression de /players car imconpatible avec essentialsx (temporaire)
=> [BUG] Suppression temp de /players

src/main/java/fr/communaywen/core/QuizManager.java, src/main/java/fr/communaywen/core/commands/ExplodeRandomCommand.java, src/main/java/fr/communaywen/core/listeners/Insomnia.java, src/main/java/fr/communaywen/core/listeners/PlayersMenuListener.java, src/main/java/fr/communaywen/core/listeners/VpnListener.java, src/main/java/fr/communaywen/core/scoreboard/ScoreboardManagers.java, src/main/java/fr/communaywen/core/utils/FreezeUtils.java, src/main/java/fr/communaywen/core/utils/PlayersMenuUtils.java, src/main/resources/plugin.yml
Correction de plusieurs fautes.
=> Correction de fautes

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/friends/commands/FriendsCommand.java, src/main/java/fr/communaywen/core/listeners/PlayersMenuListener.java, src/main/java/fr/communaywen/core/staff/players/PlayersCommand.java, src/main/java/fr/communaywen/core/utils/PlayersMenuUtils.java
*Votre code se compile t-il en local ?*:  oui
Modification du getDisplayName par getName
J'enlève le §f dans le listener pour bien récup le joueur
=> Correction de la list d'amis et correction du /players

build.gradle, src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/listeners/TablistListener.java, src/main/java/fr/communaywen/core/tab/Tablist.java, src/main/resources/plugin.yml
La tablist est désormais modifiée
=> Ajout du tablist

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/listeners/FarineListener.java
*Votre code se compile t-il en local ?*:   oui
J'ai ajouté un craft pour la farine
=> Ajout de farine pour l'agriculture ^^

src/main/java/fr/communaywen/core/listeners/ChatListener.java, src/main/java/fr/communaywen/core/listeners/OnPlayers.java
J'ai mis quelques fonction en asynchrone pour moins de lag
=> Optimisation pour éviter des lags

src/main/java/fr/communaywen/core/friends/commands/FriendsCommand.java, src/main/java/fr/communaywen/core/tab/Tablist.java
J'ai ajouté le préfix dans le tab
_j'ai un peu fail le nom du commit mais chut_
=> Ajout du préfix dans le tab

src/main/java/fr/communaywen/core/QuizManager.java
Le quiz était clear au premier message dans le chat, donc si le premier messages envoyé n'était pas la réponse le quiz était supprimé et la réponse ne s'affichait jamais
=> fix: QuizManager -> Le quiz était clear au premier message dans le chat

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/levels/ExperienceManager.java, src/main/java/fr/communaywen/core/levels/LevelCommand.java, src/main/java/fr/communaywen/core/levels/LevelsDataManager.java, src/main/resources/levels.yml
Ajout de la classe LevelComand pour la gestion de la commande /level qui permet de  gérer l'xp.
Ajout de la classe ExperienceManager qui gère le système de levels. Ajout de la classe LevelsDataManager
qui gère la sauvegarde des données dans le fichier levels.yml.
=> [feature] bases du système de levels

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/PrivacyCommand.java, src/main/java/fr/communaywen/core/listeners/ChatListener.java, src/main/java/fr/communaywen/core/listeners/OnPlayers.java, src/main/java/fr/communaywen/core/utils/database/Blacklist.java
J'ai ajouté la commande /privacy
Pour l'instant blocker désactive juste le son de "ding"
*j'ai aussi modifié la corriger la taille Seinyy*
`CREATE TABLE blacklists (Owner VARCHAR(36), Blocked VARCHAR(36))`
=> Add Blacklists

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/corpse/CorpseBlock.java, src/main/java/fr/communaywen/core/corpse/CorpseManager.java, src/main/java/fr/communaywen/core/corpse/CorpseMenu.java, src/main/java/fr/communaywen/core/listeners/CorpseListener.java
A la mort du joueur, il y a une tombe qui apparait et seul le joueur qui est mort peut récup le stuff.
Le code est pas très beau à certains endroits, vous pouvez modif.
=> Ajout du système de corps.

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/TailleCommand.java
/taille 123
taille en cm, entre 100 et 200
=> Add /taille

src/main/java/fr/communaywen/core/listeners/PlayersMenuListener.java, src/main/java/fr/communaywen/core/staff/players/PlayersCommand.java, src/main/java/fr/communaywen/core/utils/PlayersMenuUtils.java
J'ai réparé le ban du /players et ajouté un système de page
=> Ajout du système de page.

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/utils/FriendsUtils.java, src/main/java/fr/communaywen/core/utils/database/DatabaseManager.java
Lorsque le plugin démarre, ça créer les tables si elle n'existe pas
=> Init tables on startup

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/levels/LevelsCommand.java
ajoute la commande /level par défaut qui retourne son xp personnel.
ajoute des permissions sur /level.
=> [feature] ajouts mineurs sur /level

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/listeners/KebabListener.java, src/main/java/fr/communaywen/core/listeners/PasFraisListener.java
Si vous manger ça
Vous avez 10% de chance que ça sois pas frais et donc faire péter
=> Tu pets si la bouffe est pas frais

src/main/java/fr/communaywen/core/corpse/CorpseManager.java, src/main/java/fr/communaywen/core/corpse/CorpseMenu.java
[FIX] Tu peux désormais prendre le contenu de la tombe après un déco reco
Quand le serveur ferme, le stuff contenu est droppé par terre.
=> [Tombe] Réparation et ajout d'une feature

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/PrivacyCommand.java, src/main/java/fr/communaywen/core/listeners/ChatListener.java, src/main/java/fr/communaywen/core/utils/database/Blacklist.java, src/main/java/fr/communaywen/core/utils/database/DatabaseConnector.java, src/main/java/fr/communaywen/core/utils/database/DatabaseManager.java
Pour faciliter l'accès à la base de donnée, sans avoir à chaque fois à ajouter mailboxManager, maintenant vous pouvez directement utiliser : extends DatabaseConnector (et non DatabaseConnection) et vous pouvez utiliser la db avec l'attribut connection, (oubliez pas d'enlever vos anciens attribut lié à la db).
Aussi il faudra rajouter dans le fichier AywenCraftPlugin.java votre class dans la partie databaseManager.register
=> Modification de la manière d'utilisation de la base de donnée

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/RewardCommand.java, src/main/java/fr/communaywen/core/utils/database/DatabaseManager.java
Usage: /rewards [code]
pour l'instant le seul code est peluche qui donne une peluche (que je vais acheter après)
Une nouvelle table, events_rewards pour pouvoir mettre le code qu'une seul fois
=> Add /rewards

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/Managers.java, src/main/java/fr/communaywen/core/commands/FeatureCommand.java, src/main/java/fr/communaywen/core/credit/FeatureManager.java, src/main/java/fr/communaywen/core/utils/CommandUtils.java
Le /feature marche, maintenant a vous de rajouter les credits sur vos classes
=> Finished /feature

src/main/java/fr/communaywen/core/commands/TeamCommand.java, src/main/java/fr/communaywen/core/teams/Team.java, src/main/java/fr/communaywen/core/teams/TeamManager.java
=> Fixed teams

src/main/java/fr/communaywen/core/AywenCraftPlugin.java
=> Refresh custom menus

src/main/java/fr/communaywen/core/Managers.java, src/main/java/fr/communaywen/core/teams/Team.java, src/main/java/fr/communaywen/core/teams/TeamManager.java, src/main/java/fr/communaywen/core/utils/database/DatabaseManager.java
Sauvegarde les teams dans la BDD (mais pas l'inventaire)
=> Save Teams to Database

src/main/java/fr/communaywen/core/claim/ClaimConfigDataBase.java, src/main/java/fr/communaywen/core/claim/ClaimDeleteConfirmationMenu.java, src/main/java/fr/communaywen/core/claim/ClaimListener.java, src/main/java/fr/communaywen/core/claim/ClaimMenu.java, src/main/java/fr/communaywen/core/claim/RegionManager.java, src/main/java/fr/communaywen/core/commands/TeamCommand.java, src/main/java/fr/communaywen/core/teams/utils/TeamUtils.java
Fix de 2 / 3 bugs des claims + ajout du /team claimlist pour unclaim + ajout paye pour les claims
=> [Features] Claims

src/main/java/fr/communaywen/core/teams/TeamManager.java
Quand une team est chargé au démarrage il n'essaye pas de deserializer l'inventaire si il est null
200eme PR 🥳🥳🥳
=> Fix: dont deserializeItemStacks null

src/main/java/fr/communaywen/core/claim/ClaimListener.java, src/main/java/fr/communaywen/core/commands/BaltopCommand.java, src/main/java/fr/communaywen/core/commands/TailleCommand.java, src/main/java/fr/communaywen/core/economy/EconomyManager.java, src/main/java/fr/communaywen/core/listeners/OnPlayers.java, src/main/java/fr/communaywen/core/quests/QuestsMenu.java
J'ai supprimé des messages de logs
=> Remove log message

src/main/java/fr/communaywen/core/commands/FeatureCommand.java
=> [Fix] Use target name and not sender name

src/main/java/fr/communaywen/core/commands/ProutCommand.java, src/main/java/fr/communaywen/core/listeners/ChatListener.java, src/main/java/fr/communaywen/core/listeners/PasFraisListener.java, src/main/java/fr/communaywen/core/listeners/ThorHammer.java, src/main/java/fr/communaywen/core/trade/Trade.java, src/main/java/fr/communaywen/core/trade/TradeAcceptCommand.java, src/main/java/fr/communaywen/core/trade/TradeCommand.java
=> Add sounds categories

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/EventsManager.java, src/main/resources/events.yml
Spécificités: 1 nuit sur 4 et pas 2 fois d'affilée, les mobs sont plus forts et les loots sont meilleurs.
**Attention: Je n'ai pas encore appliqué les changements de Xernas, il faudra donc l'instanciation de l'EventManager dans la class Managers**
=> Ajout du premier évènement aléatoire, Nuit Terrifiante

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/TeamAdminCommand.java
Affiche la team d'un joueur
Supprime une team
Ajoute un joueur à une team
Supprime un joueur d'une team
Vide l'inventaire d'une team
=> Add teams moderation command

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/listeners/NoMoreLapins.java
Dark @dandan2611 demanda
Gyro fit
faut que tu nous explique
=> Disable rabbit

build.gradle, src/main/java/fr/communaywen/core/staff/players/PlayerDetailsMenu.java, src/main/java/fr/communaywen/core/staff/players/PlayersCommand.java, src/main/java/fr/communaywen/core/staff/players/PlayersMenu.java, src/main/java/fr/communaywen/core/teams/Team.java, src/main/resources/plugin.yml
- Ajout du OP pour executer la commande
- Ajout de la team sur la tête du joueur dans les menus
=> Modif /players

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/FallBloodCommand.java, src/main/java/fr/communaywen/core/listeners/FallBloodListener.java, src/main/resources/plugin.yml
FallBlood
*Avez vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?*: OUI
*Avez-vous supprimez les imports inutilisés ?*: NON
J'ai ajouter un Listener qui écoute lorsque les joueurs tombe ou veulent utiliser un bandage. Le bandage est recuperable avec une commande (Uniquement les ops).
Merci
=> Ajout d'un système de saignement après une chute

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/Managers.java, src/main/java/fr/communaywen/core/adminshop/menu/buy/AdminShopBuyConfirm.java, src/main/java/fr/communaywen/core/commands/MoneyCommand.java, src/main/java/fr/communaywen/core/commands/PayCommands.java, src/main/java/fr/communaywen/core/commands/TeamAdminCommand.java, src/main/java/fr/communaywen/core/quests/QuestsManager.java, src/main/java/fr/communaywen/core/teams/TeamManager.java, src/main/java/fr/communaywen/core/utils/Transaction.java, src/main/java/fr/communaywen/core/utils/TransactionsMenu.java, src/main/java/fr/communaywen/core/utils/database/DatabaseManager.java, src/main/java/fr/communaywen/core/utils/database/TransactionsManager.java
*Votre code se compile t-il en local ?*:  Oui
J'ai ajouté une commande `/money history` 
elle affiche l'historique des transactions d'un joueur (image 3)
Avec la perm `ayw.mods.history` on peut spécifier un joueur et voir ses transactions
=> Add money history

build.gradle, src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/tpa/TPACommand.java, src/main/java/fr/communaywen/core/tpa/TPAQueue.java, src/main/java/fr/communaywen/core/tpa/TpacceptCommand.java, src/main/java/fr/communaywen/core/tpa/TpcancelCommand.java, src/main/java/fr/communaywen/core/tpa/TpdenyCommand.java
J'ai update le fonctionnement du systeme TPA, ajout du GUI /tpa
j'*Avez vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?*: OUI, j'ai lu le code de conduite
*Votre code se compile t-il en local ?*: OUI, mon code ce compile bien en local
J'ai update le systeme de TPA, cooldown, un GUI si tu ecris /tpa avec la liste de joueurs, les messages sont bien clair
=> Update TPA System

gradle/wrapper/gradle-wrapper.properties, src/main/java/fr/communaywen/core/corpse/CorpseManager.java, src/main/java/fr/communaywen/core/corpse/CorpseMenu.java, src/main/java/fr/communaywen/core/listeners/CorpseListener.java
La tombe s'enlève 10 minutes après la mort du joueur
=> La tombe s'enlève 10 minutes après la mort

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/FallBloodCommand.java, src/main/java/fr/communaywen/core/fallblood/BandageRecipe.java, src/main/java/fr/communaywen/core/listeners/TablistListener.java, src/main/java/fr/communaywen/core/tab/TabList.java
*Avez vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?*: OUI
*Votre code se compile t-il en local ?*:  OUI
J'ai ajouté un craft pour les bandages
=> Added custom recipe for the bandage (Plugin de chute)

src/main/java/fr/communaywen/core/fallblood/BandageRecipe.java, src/main/java/fr/communaywen/core/listeners/FallBloodListener.java
*Avez vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?*:OUI
Fix du craft des bandages, un minimum de 7 blocks et requis pour déclencher la chute. nerf des dégâts
=> Fix dégâts de chute (FallBlood)

src/main/java/fr/communaywen/core/tpa/TPACommand.java
*Avez vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?*: OUI
Fix /tpa, maintenant un GUI s'execute
=> Fix TPACommand.java GUI

src/main/java/fr/communaywen/core/corpse/CorpseManager.java
Bah en gros j'ai fail et j'ai mis que la tombe despawn en 1min au lieu de 10. Donc maintenant c'est réglé
=> correction du despawn de la tombe

src/main/java/fr/communaywen/core/corpse/CorpseManager.java, src/main/java/fr/communaywen/core/listeners/CorpseListener.java, src/main/java/fr/communaywen/core/scoreboard/GlobalTeamManager.java
Si tu meurs sur un demi bloc, le demi bloc n'est plus supprimé
=> [FIX] Tombe : réparation de la mort sur demi bloc

src/main/java/fr/communaywen/core/tpa/TPACommand.java, src/main/java/fr/communaywen/core/tpa/TPACommandGUI.java, src/main/java/fr/communaywen/core/tpa/TPAMenu.java
J'ai juste fix le probleme du 'You need to specify a value for the joueur!'
=> Fix TPACommand.java GUI x2

src/main/java/fr/communaywen/core/Managers.java, src/main/java/fr/communaywen/core/teams/Team.java, src/main/java/fr/communaywen/core/teams/TeamManager.java, src/main/java/fr/communaywen/core/teams/cache/TeamCache.java
Optimisation du TeamList (ajout d'un cache)
=> Optimisation du TeamList

src/main/java/fr/communaywen/core/scoreboard/ScoreboardManager.java, src/main/java/fr/communaywen/core/teams/TeamManager.java, src/main/java/fr/communaywen/core/teams/cache/TeamCache.java
=> Correction du onLoad pour la database

src/main/java/fr/communaywen/core/teams/Team.java, src/main/java/fr/communaywen/core/teams/TeamManager.java, src/main/java/fr/communaywen/core/teams/cache/TeamCache.java
=> [Fix] Cette fois , le système de team bug plus

src/main/java/fr/communaywen/core/teams/TeamManager.java, src/main/java/fr/communaywen/core/teams/menu/TeamMenu.java
Le /team list était déjà optimisé mais je savais pas que c'était pas uniquement le base de donné qui faisait lag (même si c'était à causé d'elle majoritairement) du coup j'ai opti le GUI et maintenant je ne ferai plus rien en rapport avec le système de Team car ça ma soulé mdr
=> [Opti] Optimisation du GUI /team list

src/main/java/fr/communaywen/core/tpa/TPACommand.java
Rework Messages
Fix cette erreur:
=> Fix @Named "joueur"

src/main/java/fr/communaywen/core/trade/Trade.java
Oui
Oui
Oui
- clear both inventories
- close inventories for both players
=> FIX - Trade Duplication Glitch

src/main/java/fr/communaywen/core/tpa/TPACommand.java, src/main/java/fr/communaywen/core/tpa/TPACommandGUI.java, src/main/java/fr/communaywen/core/tpa/TPAGUICommand.java
*Avez vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?*: OUI
Ajoute commande /tpagui
=> Add TPAGui

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/listeners/BabyFuzeListener.java
Ajout d'un bébé fuze qui a une chance sur 10 de spawn si tu tues un villageois.
=> [FEATURE] Bébé Fuze

src/main/java/fr/communaywen/core/AywenCraftPlugin.java
Avec 1 de sandstone on obtient 4 de sables
=> Ajout d'un craft pour transformer la sandstone en sable

src/main/java/fr/communaywen/core/teams/menu/TeamListMenu.java
Oui
Oui
Ajout de la mise en cache des objets ItemStack pour éviter leur recréation multiple.
Utilisation de computeIfAbsent pour créer les objets uniquement si nécessaire.
Simplification du code et suppression des variables inutiles pour améliorer les performances et la lisibilité.
=> Meek : Optimisation du /team list qui faisait décendre le tps du serveur

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/Managers.java, src/main/java/fr/communaywen/core/commands/teams/TeamCommand.java, src/main/java/fr/communaywen/core/commands/utils/ChatChannelCMD.java, src/main/java/fr/communaywen/core/listeners/ChatListener.java, src/main/java/fr/communaywen/core/teams/Team.java, src/main/java/fr/communaywen/core/utils/chatchannel/Channel.java, src/main/java/fr/communaywen/core/utils/chatchannel/PlayerChatChannel.java
J'ai ajouté un channel Team et un channel Global dans le chat (/channel <GLOBAL:TEAM>)
=> Ajout des channels dans le chat

src/main/java/fr/communaywen/core/AywenCraftPlugin.java
Oui
Oui
Oui
Ajout de la crazy potion
=> Ajout de la crazy potion

src/main/java/fr/communaywen/core/listeners/SleepListener.java
Modification des credits de SleepListener pour un nom de feature plus court
=> Modification des credits de SleepListener

src/main/java/fr/communaywen/core/quests/qenum/TYPE.java
Ajout du type DEATH (pour l'affichage)
Oui
Oui (avec les autres partie (voir autre pull requests concernant les quetes))
*Avez-vous supprimez les imports inutilisés ?*:
Oui 
Ajout d'un type de Quêtes pour l'affichage propre
=> Ajout d'un type de Quêtes pour l'affichage propre {PARTIE 1 quetes}

src/main/java/fr/communaywen/core/listeners/VpnListener.java
from ip-api.com to ip.notri1.fr
=> [FIX] Changed AntiVPN API

src/main/java/fr/communaywen/core/utils/MOTDChanger.java
Logical change of version
Avez vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?:
OUI
Votre code se compile t-il en local ?:
OUI
Avez-vous supprimez les imports inutilisés ?:
OUI
Decrivez vos changements
Clairement et avec des screenshots si nécessaires
Changement logique des MOTDs random pour modifier la version: 1.20.6 >> 1.21
=> Logical Change

src/main/java/fr/communaywen/core/EventsManager.java
Patch V2
> Oui
> Oui
> Oui
J'ai reffet la fonction pour modifier clearTerrifyingNight c'est pour moi le seul truc qui peut bloquer
=> Update EventsManager.java - Patch clearTerrifyingNight

src/main/java/fr/communaywen/core/EventsManager.java, src/main/java/fr/communaywen/core/quests/QuestsListener.java, src/main/java/fr/communaywen/core/quests/qenum/QUESTS.java, src/main/java/fr/communaywen/core/quests/qenum/TYPE.java
Récupérer une relique du pain sacré, planter et faire grandir 10 arbres avec de la bonemeal, réussir un jump au spawn (il faudra le build et entrer les bonnes coordonnées)
=> Fix Nuit terrifiante + Ajoute 3 quêtes: Le pain sacré, Sauvons la planète, Saute comme un ninja

src/main/java/fr/communaywen/core/AywenCraftPlugin.java
> Oui
> Oui
> Oui
Il faut quel OneShot les block au prix quelle coute donc buff
=> Update AywenCraftPlugin.java -- Buff Mining Potion

src/main/java/fr/communaywen/core/quests/QuestsListener.java
J'ai commit sur téléphone 💀
J'espère 💀
=> Fix de la quête "Le pain sacré"

src/main/java/fr/communaywen/core/staff/report/ReportCache.java
Suppression du staff/report/ReportCache.java
=> Suppression d'un fichier inutile

src/main/java/fr/communaywen/core/claim/ClaimListener.java, src/main/java/fr/communaywen/core/dreamdim/listeners/CloudSoup.java, src/main/java/fr/communaywen/core/dreamdim/listeners/EnterWorldListener.java
Fix: Annuler le fly après une reconnection
=> Fix de bugs

src/main/java/fr/communaywen/core/Managers.java, src/main/java/fr/communaywen/core/dreamdim/listeners/CloudSoup.java, src/main/java/fr/communaywen/core/scoreboard/ScoreboardManager.java
*Avez vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?*: `true`
*Avez-vous supprimez les imports inutilisés ?*:  oui
Problème: ça s'actualise 1x/minutes c'est pas top
=> Ajout du temps de vol dans le scoreboard

src/main/java/fr/communaywen/core/claim/ClaimConfigDataBase.java, src/main/java/fr/communaywen/core/claim/ClaimListener.java, src/main/java/fr/communaywen/core/claim/ClaimMenu.java, src/main/java/fr/communaywen/core/claim/ClaimParticleTask.java, src/main/java/fr/communaywen/core/claim/GamePlayer.java, src/main/java/fr/communaywen/core/claim/RegionManager.java, src/main/java/fr/communaywen/core/commands/teams/TeamClaim.java, src/main/java/fr/communaywen/core/teams/Team.java, src/main/java/fr/communaywen/core/utils/database/DatabaseManager.java
Ajout d'une wand pourvoir les informations d'un claim craftable avec de l'or et deux sticks.
Ajout de particule autours d'un claim pour y voir les limites
Ajout d'un message pour voir qui as claim
=> Update sur les claims

src/main/java/fr/communaywen/core/claim/ClaimConfigDataBase.java, src/main/java/fr/communaywen/core/claim/ClaimListener.java, src/main/java/fr/communaywen/core/claim/ClaimMenu.java, src/main/java/fr/communaywen/core/claim/ClaimParticleTask.java, src/main/java/fr/communaywen/core/claim/GamePlayer.java, src/main/java/fr/communaywen/core/claim/RegionManager.java, src/main/java/fr/communaywen/core/commands/teams/TeamClaim.java, src/main/java/fr/communaywen/core/teams/Team.java, src/main/java/fr/communaywen/core/utils/database/DatabaseManager.java
Reverts ServerOpenMC/Plugin#410
=> Revert "Revert "Update sur les claims""

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/claim/ClaimConfigDataBase.java
Ajout d'un cache temporaire pour load les claims
=> [Bug] Add temporary cache for load claim

src/main/java/fr/communaywen/core/AywenCraftPlugin.java
> Oui
> Oui
> Oui
Ajout de l'init de la crazy potion qui avait été enlever par ???
=> Update AywenCraftPlugin.java -- Ajout d'init de la recipe crazy potion

src/main/java/fr/communaywen/core/space/moon/MoonListener.java
Fixed Nether Portals, not suffocating after reconnecting on moon without glass, and possibly a bug with explosions on moon where you could get the vanilla drop instead of the "custom" drop.
=> [Fixes] Fixed bugs on moon

src/main/java/fr/communaywen/core/contest/ContestListener.java, src/main/java/fr/communaywen/core/contest/ContestManager.java, src/main/java/fr/communaywen/core/contest/FirerocketSpawnListener.java
*Avez-vous supprimez les imports inutilisés ?*:  oui
Vraiment désolé, j'ai oublié d'ajouter une condition lorsque j'ai fait le code 
Vous pourrez la pr quand les conflits avec la feature des lucky block sera fait et que j'aurais enlevé les commentaires sur mon code pour ajouter les lucky block en rewards
=> Un Oublie - Contest

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/contest/ContestManager.java, src/main/java/fr/communaywen/core/contest/menu/ContributionMenu.java, src/main/java/fr/communaywen/core/contest/menu/MoreInfoMenu.java, src/main/java/fr/communaywen/core/contest/menu/TradeMenu.java, src/main/java/fr/communaywen/core/listeners/CustomFlagsEvents.java, src/main/java/fr/communaywen/core/listeners/ThorHammer.java, src/main/java/fr/communaywen/core/mailboxes/MailboxManager.java
*Votre code se compile t-il en local ?*: ouii
*Avez-vous supprimez les imports inutilisés ?*:  oui
Des bugs fix tel que un probleme d'addition des points pour chaque joueur, un probleme avec les rangs
Ajout de petites choses pour rendre la fonctionnalité plus complete
=> Bugs - Contest

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/Managers.java, src/main/java/fr/communaywen/core/contest/menu/ConfirmMenu.java, src/main/java/fr/communaywen/core/customitems/items/BuilderWand.java, src/main/java/fr/communaywen/core/customitems/items/DiamondHammer.java, src/main/java/fr/communaywen/core/customitems/items/IronHammer.java, src/main/java/fr/communaywen/core/customitems/items/NetheriteHammer.java, src/main/java/fr/communaywen/core/customitems/managers/CustomItemsManager.java, src/main/java/fr/communaywen/core/listeners/ThorHammer.java, src/main/resources/config.yml
*Votre code se compile t-il en local ?*:  oui
Ajouts des flags de disable-hammer et disable-builder-wand
Des patch, et un changement d'item : SLIME_BLOCK => SHROOMLIGHT
=> Last Fixes

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/EventsManager.java, src/main/java/fr/communaywen/core/personalhome/HSCommand.java, src/main/java/fr/communaywen/core/personalhome/Home.java, src/main/java/fr/communaywen/core/personalhome/HomeManager.java, src/main/java/fr/communaywen/core/personalhome/HomesUtils.java, src/main/java/fr/communaywen/core/personalhome/listeners/BuildRestrictions.java, src/main/java/fr/communaywen/core/utils/database/DatabaseManager.java, src/main/resources/plugin.yml
Vous pouvez activé les visites (par défaut elles désactivés) avec `/maison allowvisit true/false`
Vous pouvez visiter avec `/maison visit joueur` (besoin de la perm ayw.maisons.visit)
et /maison find joueur pour trouver la maison de qqn (besoin de la perm ayw.maisons.locate)
=> /maison visit et /maison find

src/main/java/fr/communaywen/core/QuizManager.java, src/main/java/fr/communaywen/core/commands/contest/ContestCommand.java, src/main/java/fr/communaywen/core/contest/ContestListener.java, src/main/java/fr/communaywen/core/contest/ContestManager.java, src/main/java/fr/communaywen/core/contest/FirerocketSpawnListener.java, src/main/java/fr/communaywen/core/contest/menu/MoreInfoMenu.java, src/main/java/fr/communaywen/core/contest/menu/VoteMenu.java, src/main/java/fr/communaywen/core/listeners/OnPlayers.java, src/main/java/fr/communaywen/core/scoreboard/ScoreboardManager.java
Des optimisations sur les Contest, apres cela mis sur le serveur pourriez vous me dire si ça va mieux?
=> Optimisation of Contest

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/Managers.java, src/main/java/fr/communaywen/core/commands/contest/ContestCommand.java, src/main/java/fr/communaywen/core/commands/corpse/CorpseCommand.java, src/main/java/fr/communaywen/core/commands/economy/BaltopCommand.java, src/main/java/fr/communaywen/core/contest/ContestManager.java, src/main/java/fr/communaywen/core/contest/FirerocketSpawnListener.java, src/main/java/fr/communaywen/core/contest/menu/ContributionMenu.java, src/main/java/fr/communaywen/core/contest/menu/MoreInfoMenu.java, src/main/java/fr/communaywen/core/corpse/CorpseManager.java, src/main/java/fr/communaywen/core/listeners/CorpseListener.java, src/main/java/fr/communaywen/core/listeners/LeaderboardListener.java, src/main/java/fr/communaywen/core/managers/LeaderboardManager.java, src/main/java/fr/communaywen/core/scoreboard/ScoreboardManager.java, src/main/resources/config.yml
Suite a un profileur : https://spark.lucko.me/svxSR4WhWl
Je pense qu'il est mieux de supprimer les Contest du Scoreboard pour éviter que cela fasse buger voir enterrer le serveur
=> A Update avant le Live d'Aywen

src/main/java/fr/communaywen/core/contest/ContestManager.java, src/main/java/fr/communaywen/core/contest/FirerocketSpawnListener.java, src/main/java/fr/communaywen/core/luckyblocks/events/neutrals/LBLeakContest.java, src/main/java/fr/communaywen/core/luckyblocks/managers/LuckyBlockManager.java
J'ai ajouté des petites nouveautés, un evenement de Lucky Block qui pourra leak le prochain theme du Contest
Et une condition qui vérifie pour faire spawner des Firerocket, c'est a dire une condition qui regarde si il y a un joueur dans le spawn
=> Ajouts sur les Contest

build.gradle, src/main/java/fr/communaywen/core/listeners/KebabListener.java, src/main/java/fr/communaywen/core/space/moon/MoonListener.java, src/main/java/fr/communaywen/core/utils/Skull.java
=> [Fix] Custom Skulls

src/main/java/fr/communaywen/core/QuizManager.java
J'ai tenté un truc qui regroupe la données "points" + le camp du joueur
=> Try to fix a bug with points0 SQL

src/main/java/fr/communaywen/core/contest/ContestManager.java, src/main/resources/config.yml
Avant les optimisations : https://spark.lucko.me/CySIJITMVd
Apres : https://spark.lucko.me/BngynYQbUV
N'hésitez pas a me dire si il y a une chose qui pourrait être optimisé, j'ai fait de mon mieux ^^
=> Fix bugs on End Contest

build.gradle, src/main/java/fr/communaywen/core/Managers.java, src/main/java/fr/communaywen/core/guideline/GrantRoot.java, src/main/java/fr/communaywen/core/guideline/GuidelineManager.java, src/main/java/fr/communaywen/core/guideline/README.md, src/main/java/fr/communaywen/core/guideline/advancements/dream/FirstDream.java, src/main/java/fr/communaywen/core/guideline/listeners/dream/FirstDream.java, src/main/resources/plugin.yml
J'ai ajouté un menu de succès, il y as déjà le succès racine et le "premier rêve" pour donner un example,
Je vais m'occuper de migrer les succès des rêves
Il faut ajouter le plugin [UltimateAdvancementAPI](https://github.com/frengor/UltimateAdvancementAPI)
=> Ajout des succès

src/main/java/fr/communaywen/core/settings/SettingsMenu.java
Retrait de l'affichage du status
=> Correction erreur /settings (desactiv temp. d'une fonctionnalité)

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/Managers.java, src/main/java/fr/communaywen/core/QuizManager.java, src/main/java/fr/communaywen/core/commands/contest/ContestCommand.java, src/main/java/fr/communaywen/core/contest/cache/ContestCache.java, src/main/java/fr/communaywen/core/contest/cache/ContestDataCache.java, src/main/java/fr/communaywen/core/contest/managers/ContestManager.java, src/main/java/fr/communaywen/core/contest/menu/ContributionMenu.java, src/main/java/fr/communaywen/core/contest/menu/TradeMenu.java, src/main/java/fr/communaywen/core/contest/menu/VoteMenu.java, src/main/java/fr/communaywen/core/mailboxes/MailboxListener.java, src/main/java/fr/communaywen/core/quests/QuestsListener.java, src/main/java/fr/communaywen/core/scoreboard/ScoreboardManager.java, src/main/resources/config.yml
J'ai ajouté une méthode qui permet de faire les requetes SQL dans un autre thread
=> Donc le bug de performance quand on quitte et quand on rejoint
=> Fix sur des bugs de performances + Mini Update sur les Contest

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/commands/utils/Patchlogs.java, src/main/java/fr/communaywen/core/commands/utils/RulesCommand.java, src/main/java/fr/communaywen/core/guideline/GuidelineManager.java
=> Add patchlogs

src/main/java/fr/communaywen/core/contest/managers/ContestManager.java, src/main/resources/config.yml
*Votre code se compile t-il en local ?*: ouii
*Avez-vous supprimez les imports inutilisés ?*: ouiii
j'ai ajouté un multiplicateur d'infériorité pour les Contest pour que ça soit plus équilibré lors des résultats, approuvé par les joueurs
Et ainsi que le craft des frites, le namespace le voici : [aywen.zip](https://github.com/user-attachments/files/17440416/aywen.zip)
Encore désolé pour touts ces changements
=> Little Update

src/main/java/fr/communaywen/core/EventsManager.java, src/main/java/fr/communaywen/core/QuizManager.java, src/main/java/fr/communaywen/core/commands/contest/ContestCommand.java, src/main/java/fr/communaywen/core/commands/spawn/head/HeadCommand.java, src/main/java/fr/communaywen/core/commands/spawn/jump/JumpCommand.java, src/main/java/fr/communaywen/core/contest/cache/ContestCache.java, src/main/java/fr/communaywen/core/contest/managers/ContestManager.java, src/main/java/fr/communaywen/core/contest/menu/ConfirmMenu.java, src/main/java/fr/communaywen/core/contest/menu/ContributionMenu.java, src/main/java/fr/communaywen/core/economy/EconomyData.java, src/main/java/fr/communaywen/core/listeners/OnPlayers.java, src/main/java/fr/communaywen/core/listeners/ParticleListener.java, src/main/java/fr/communaywen/core/luckyblocks/managers/LBPlayerManager.java, src/main/java/fr/communaywen/core/luckyblocks/utils/LBReminder.java, src/main/java/fr/communaywen/core/managers/LeaderboardManager.java, src/main/java/fr/communaywen/core/scoreboard/ScoreboardManager.java, src/main/java/fr/communaywen/core/spawn/head/HeadListener.java, src/main/java/fr/communaywen/core/spawn/head/HeadManager.java, src/main/java/fr/communaywen/core/tpa/TPACommand.java, src/main/java/fr/communaywen/core/utils/database/DatabaseManager.java
J'ai oublié ces méthodes a optimiser dans les Contests et j'ai corrigé 2 erreurs sur la commande jump et heads
=> Optimisation des Contests + Petites Modifications

src/main/java/fr/communaywen/core/AywenCraftPlugin.java, src/main/java/fr/communaywen/core/adminshop/AdminShopCategory.java, src/main/java/fr/communaywen/core/adminshop/menu/AdminShopMenu.java, src/main/java/fr/communaywen/core/adminshop/menu/buy/AdminShopBuy.java, src/main/java/fr/communaywen/core/adminshop/menu/category/colored/BlockType.java, src/main/java/fr/communaywen/core/adminshop/menu/category/defaults/BlocksItems.java, src/main/java/fr/communaywen/core/adminshop/menu/category/defaults/MiscItems.java, src/main/java/fr/communaywen/core/adminshop/menu/category/defaults/OresItems.java, src/main/java/fr/communaywen/core/adminshop/menu/sell/AdminShopSell.java, src/main/java/fr/communaywen/core/adminshop/shopinterfaces/BaseItems.java, src/main/java/fr/communaywen/core/claim/ClaimConfigDataBase.java, src/main/java/fr/communaywen/core/claim/ClaimListener.java, src/main/java/fr/communaywen/core/claim/ClaimMenu.java, src/main/java/fr/communaywen/core/claim/RegionManager.java, src/main/java/fr/communaywen/core/commands/contest/ContestCommand.java, src/main/java/fr/communaywen/core/listeners/CustomFlagsEvents.java, src/main/java/fr/communaywen/core/listeners/OnPlayers.java, src/main/java/fr/communaywen/core/luckyblocks/managers/LBPlayerManager.java, src/main/java/fr/communaywen/core/spawn/head/HeadManager.java, src/main/java/fr/communaywen/core/spawn/jump/JumpListener.java, src/main/java/fr/communaywen/core/tpa/TPACommand.java, src/main/java/fr/communaywen/core/tpa/TPAQueue.java, src/main/java/fr/communaywen/core/tpa/TpacceptCommand.java, src/main/java/fr/communaywen/core/tpa/TpcancelCommand.java, src/main/java/fr/communaywen/core/tpa/TpdenyCommand.java, src/main/java/fr/communaywen/core/utils/constant/Prefix.java
*Avez vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?*: ouiii
*Votre code se compile t-il en local ?*: ouii
J'ai ajouté des protections en plus sur le Jump (genre si on fly, si on se tp, si on vole en elytra, je vous laisse regarder)
J'ai aussi fait le style des commandes TPA qui sont pas mal utilisé par les joueurs
=> Mini Update du Dimanche - Les Jumps et Plus

src/main/java/fr/communaywen/core/commands/homes/HomesCommands.java, src/main/java/fr/communaywen/core/homes/HomesManagers.java, src/main/java/fr/communaywen/core/homes/menu/utils/HomeMenuUtils.java
J'ai remove les debug pour les homes car spam
=> Removing debug for homes system

src/main/java/fr/communaywen/core/guideline/listeners/dream/HelldiversManager.java
J'ai utilisé un batch pour sauvegarder les succès
=> Use batch for saving advancements

src/main/java/fr/communaywen/core/economy/EconomyManager.java
Fix une erreur qui empechait l'execution de la fin du Contest, svp mettez la au plus vite sur le serveur j'ai pas envie de me presser a la derniere minute. 
Merci
=> Fix pq is null - A METTRE AU PLUS VITE

src/main/java/fr/communaywen/core/economy/EconomyManager.java
=> Dernier fix sur le saveBalance avec le player Offline

src/main/java/fr/communaywen/core/managers/LeaderboardManager.java
https://mclo.gs/RyBfV57
Redite moi sur les logs je vois que la méthode getTopPlayTime qui est censé faire bugé
=> Encore un Fix

src/main/java/fr/communaywen/core/contest/managers/ContestManager.java
`[18:41:56 INFO]: iambibi_ issued server command: /contest setphase 3
[18:41:56 INFO]: iambibi_ lost connection: Procédure de Fin du Contest
Cela devrait prendre quelques minutes
[18:41:56 INFO]: [-] Adiniambibi_
[18:41:57 INFO]:                                                      
CONTEST! Time over! 
Fin du Contest, retrouvez vos récompenses et le bilan de ce Contest
sous forme de livre
*/contest pour voir quand le prochain contest arrive*
[18:41:57 INFO]: Vous avez reçu la lettre du Contest
Cliquez-ici pour ouvrir la mailbox …
=> Fix sur la fin de contest

src/main/java/fr/communaywen/core/AywenCraftPlugin.java
*Avez vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?*: yep
*Votre code se compile t-il en local ?*: yep
*Avez-vous supprimez les imports inutilisés ?*: yep
Juste un ajout dans le Main pour éviter une erreur lors du /settings
Jsp pk le Listener s'était retiré
=> Add SettingsListerner to register events
